// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katz.coursemanager.model;

import com.katz.coursemanager.model.Student;
import javax.persistence.Entity;

privileged aspect Student_Roo_Jpa_Entity {
    
    declare @type: Student: @Entity;
    
}
